css-positioning - Dennis Liu
dennisliu9/c0522-code-solutions pull request #19
Opened 2022-05-13 17:54 UTC by dennisliu9

![css-positioning_relative_solution](https://user-images.githubusercontent.com/21215658/168340366-78fe4d2a-b7ea-4023-95fb-a9254b8b6e59.PNG)
![css-positioning_absolute_solution](https://user-images.githubusercontent.com/21215658/168340376-be278cac-91cc-41e7-88df-ac8b1ce9d470.PNG)
![css-positioning_fixed_solution](https://user-images.githubusercontent.com/21215658/168340385-afcb8430-34a9-4311-8bf9-57e7b1c350e5.gif)

2022-05-14 23:23 UTC, codingcodymiller requested changes

2022-05-14 23:23 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  left: 30%;
If you make the title `width: 100%`, this won't be necessary, since `text-align: center;` has already been applied

2022-05-15 04:33 UTC, dennisliu9 commented on css-positioning/fixed.css
> +  left: 30%;
Usually an h1 element will take up the entire width since it's a block element, but by making it `position: fixed;` it is taken out of the regular document flow and the idea of "taking up the entire width" is then a bit funky, is that right?

2022-05-15 19:48 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  left: 30%;
That is correct!

2022-05-15 19:52 UTC, codingcodymiller approved these changes

2022-05-15 22:50 UTC, merged