css-two-column-layout - Dennis Liu
dennisliu9/c0522-code-solutions pull request #20
Opened 2022-05-13 22:48 UTC by dennisliu9

![css-two-column-layout_solution](https://user-images.githubusercontent.com/21215658/168398526-295d53e0-5974-4b9f-97e3-29ed375c07e2.PNG)

As usual, my solution is on the left while the reference is on the right.

2022-05-14 22:44 UTC, codingcodymiller requested changes

2022-05-14 22:44 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
I think you can forego doing a lot of this by just making a nested `row` within `column-half` (what you have currently as `card`) elements, one for each section in the second row.

2022-05-15 05:58 UTC, dennisliu9 commented
![css-two-column-layout_solution2](https://user-images.githubusercontent.com/21215658/168459288-8c1a7e42-4932-4f08-aedb-7f432bc71c57.PNG)

Revisions made code much clearer. Image is of updated results on the left against the example on the right.

2022-05-15 19:31 UTC, codingcodymiller approved these changes
Excellent work!

2022-05-15 22:51 UTC, merged